<a href="https://colab.research.google.com/github/ParvinGhaffarzadeh/Natural_Language_Processing_Projects/blob/main/Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from nltk import sent_tokenize

In [ ]:
import re

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [ ]:
txt = """A major drawback of statistical methods is that they require elaborate feature engineering. 
Since the early 2010s, the field has thus largely abandoned statistical methods and shifted to neural networks for machine learning. 
Popular techniques include the use of word embeddings to capture semantic properties of words, and an increase in end-to-end learning of a higher-level task (e.g., question answering) instead of relying on a pipeline of separate intermediate tasks (e.g., part-of-speech tagging and dependency parsing).
In some areas, this shift has entailed substantial changes in how NLP systems are designed, such that deep neural network-based approaches may be viewed as a new paradigm distinct from statistical natural language processing. 
For instance, the term neural machine translation (NMT) emphasizes the fact that deep learning-based approaches to machine translation directly learn sequence-to-sequence transformations, obviating the need for intermediate steps such as word alignment and language modeling that was used in statistical machine translation (SMT). 
Latest works tend to use non-technical structure of a given task to build proper neural network
"""

In [ ]:
#cleaning text
sent=sent_tokenize(txt)

In [ ]:
sent

['A major drawback of statistical methods is that they require elaborate feature engineering.',
 'Since the early 2010s, the field has thus largely abandoned statistical methods and shifted to neural networks for machine learning.',
 'Popular techniques include the use of word embeddings to capture semantic properties of words, and an increase in end-to-end learning of a higher-level task (e.g., question answering) instead of relying on a pipeline of separate intermediate tasks (e.g., part-of-speech tagging and dependency parsing).',
 'In some areas, this shift has entailed substantial changes in how NLP systems are designed, such that deep neural network-based approaches may be viewed as a new paradigm distinct from statistical natural language processing.',
 'For instance, the term neural machine translation (NMT) emphasizes the fact that deep learning-based approaches to machine translation directly learn sequence-to-sequence transformations, obviating the need for intermediate step

In [ ]:
stemmer = PorterStemmer()

In [ ]:
corpus=[]

In [ ]:
for s in sent:
    review=re.sub("[^a-zA-Z]"," ",s) #jaygozin ba space dar khode s
    review=re.sub("\b[a-zA-Z]\b"," ",review)
    review=review.lower()
    review=review.split()
    review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = " ".join(review)
    corpus.append(review)
    print(review)
    print("\n")

major drawback statist method requir elabor featur engin


sinc earli field thu larg abandon statist method shift neural network machin learn


popular techniqu includ use word embed captur semant properti word increas end end learn higher level task e g question answer instead reli pipelin separ intermedi task e g part speech tag depend pars


area shift entail substanti chang nlp system design deep neural network base approach may view new paradigm distinct statist natur languag process


instanc term neural machin translat nmt emphas fact deep learn base approach machin translat directli learn sequenc sequenc transform obviat need intermedi step word align languag model use statist machin translat smt


latest work tend use non technic structur given task build proper neural network




In [ ]:
corpus

['major drawback statist method requir elabor featur engin',
 'sinc earli field thu larg abandon statist method shift neural network machin learn',
 'popular techniqu includ use word embed captur semant properti word increas end end learn higher level task e g question answer instead reli pipelin separ intermedi task e g part speech tag depend pars',
 'area shift entail substanti chang nlp system design deep neural network base approach may view new paradigm distinct statist natur languag process',
 'instanc term neural machin translat nmt emphas fact deep learn base approach machin translat directli learn sequenc sequenc transform obviat need intermedi step word align languag model use statist machin translat smt',
 'latest work tend use non technic structur given task build proper neural network',
 'major drawback statist method requir elabor featur engineering.',
 'sinc earli 2010s, field thu larg abandon statist method shift neural network machin learning.',
 'popular techniqu incl

In [ ]:
#vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(corpus).toarray()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tfidf = tf.fit_transform(corpus).toarray()

In [ ]:
print(bow)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 1]]


In [ ]:
print(tfidf)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.32873797 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.27327222 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.15637232 ... 0.12114881 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.29994044]]
